DROP TABLE IF EXISTS `room`;
DROP TABLE IF EXISTS `lecturer`;
DROP TABLE IF EXISTS `department`;
DROP TABLE IF EXISTS `batch`;
DROP TABLE IF EXISTS `subject`;
DROP TABLE IF EXISTS `course`;
DROP TABLE IF EXISTS `class`;